### ISSUE TITLE
Add option to limit response size

### ISSUE THREAD

**Issue by nguyenq9** [wwu-webtech/descriptive-alt-text-generator#10]
This can look like a checkbox or radio button underneath the file/link input field that will allow the user to "limit" the characters the response to below 260 characters.

Another option can be to have an additional field so users can specify the character limit themselves.

**Comment by davidengebretson** [comment]
Maybe just a setting under the personalized settings page? No need to clutter up the UI.


From: Thai Nguyen ***@***.***>
Sent: Thursday, April 18, 2024 10:26 AM
To: wwu-webtech/descriptive-alt-text-generator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwu-webtech/descriptive-alt-text-generator] Add option to limit response size (Issue #10)


This can look like a checkbox or radio button underneath the file/link input field that will allow the user to "limit" the characters the response to below 260 characters.

Another option can be to have an additional field so users can specify the character limit themselves.

-

**Comment by nguyenq9** [comment]
Alex and I were playing around with the idea of a dropdown for advanced options sort of like how the refine results component is currently set up. That way it'll still be compact, and users can customize their query every time.

**Comment by davidengebretson** [comment]
Go forth! Make it happen. 😊
I’ve also updated the OneDrive file to reflect current changes and ideas.
