### ISSUE TITLE
Batch Upload

### ISSUE THREAD

**Issue by nguyenq9** [wwu-webtech/descriptive-alt-text-generator#11]
User feedback indicates that there should be a batch upload feature.

Things to consider:
- what is the upper limit of images that can be uploaded?
- how should the information be displayed?
- should all the information be served at once or as they are being completed?
- how will users know which description belongs to which image?

**Comment by davidengebretson** [comment]
All good questions. If it were up to me I'd say no batch upload should be allowed. But, I'm not your typical user... 15 seconds for ChatGPT to respond? If a user were to batch upload 20 photos then that would be 5 minutes to wait for all items to complete. That's way too long. We need something like "lazy loading" to reduce the UX impact. I'm not sure if I'm using lazy loading correctly. But...

I think the first image that gets a full response from the AI engines should be presented first. Then start loading the other pictures in the background of a switcher or list view that will give the user context. Kind of like a "pagination" that people can quickly jump between results. If, for example, the user batch uploads a bunch of photos that are really similar, then they'll probably want to see the picture and see the fluffy AI text in an uncluttered environment. I'd say "keep it simple" for now. Future user feedback may change our design direction after the simple solution is developed.

Plus, don't feel like you need to jump on every whim from a user. I'd say, "work on the prioritized issues", keep the feedback from the user in the back of your head, and keep up the great work!


From: Thai Nguyen ***@***.***>
Sent: Thursday, April 18, 2024 10:30 AM
To: wwu-webtech/descriptive-alt-text-generator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwu-webtech/descriptive-alt-text-generator] Batch Upload (Issue #11)


User feedback indicates that there should be a batch upload feature.

Things to consider:

  *   what is the upper limit of images that can be uploaded?
  *   how should the information be displayed?
  *   should all the information be served at once or as they are being completed?
  *   how will users know which description belongs to which image?

-
