### ISSUE TITLE
Add Copy & Paste button to output fields

### ISSUE THREAD

**Issue by alexkefer** [wwu-webtech/descriptive-alt-text-generator#12]
Add a button for each output box to easily copy the text. Ideally will use an icon with an accessible alternative description.

**Comment by davidengebretson** [comment]
Perfect. Will it be an icon of scissors like it was 30 years ago when I could see the screen?


From: alex kefer ***@***.***>
Sent: Thursday, April 18, 2024 10:33 AM
To: wwu-webtech/descriptive-alt-text-generator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwu-webtech/descriptive-alt-text-generator] Add Copy & Paste button to output fields (Issue #12)


Add a button for each output box to easily copy the text. Ideally will use an icon with an accessible alternative description.

-
