### ISSUE TITLE
Add a modal for responsible use 

### ISSUE THREAD

**Issue by nguyenq9** [wwu-webtech/descriptive-alt-text-generator#36]
After the user clicks on the copy text button there should be, by default, a modal that pops up reminding them about using the tool responsibly. This modal can be disabled in the advanced options dropdown.

**Comment by davidengebretson** [comment]
Oooh, I like the idea of making the modal dialog a responsible use issue.

Perhaps we should even have the responsible use acceptance during the login process?

I think duplicating the responsible use acceptance is relevant in both cases. Maybe more throughout the DATG UX?

Thanks,
David


From: Thai Nguyen ***@***.***>
Sent: Wednesday, May 22, 2024 10:40 PM
To: wwu-webtech/descriptive-alt-text-generator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwu-webtech/descriptive-alt-text-generator] Add a modal for responsible use (Issue #36)


-

**Comment by nguyenq9** [comment]
@davidengebretson I added the modal as requested. If you can take a look at the message for responsible use inside and give some feedback that would be great. You can also turn off the modal popup under the "Other" section in "Advanced Options".

**Comment by davidengebretson** [comment]
It looks pretty good to me. I'll have to ask Max what he thinks.
